import AnimalCard from '@/components/AnimalCard';
import React from 'react';

export const metadata = {
  title: "livestock-booking-platform all-animals",
  description: "Generated by create next app",
};

const AllAnimalsPage = async() => {
  const res = await fetch('http://localhost:3000/data.json',{
    cache: 'no-store'
  });
  const animals = await res.json(); 
  console.log(animals)
  
  return (
    <div>
      <h1 className='text-2xl font-bold my-5'>All Animals</h1>
      <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5'>
        {animals.map(animal => (
          <AnimalCard key={animal.id} animal={animal} />
        ))}
      </div>
    </div>
  );
};

export default AllAnimalsPage;