import AnimalCard from '@/components/AnimalCard';
import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: "livestock-booking-platform all-animals",
  description: "Generated by create next app",
};

const AllAnimalsPage = async({searchParams}) => {
   const sort = searchParams.sort;
  const res = await fetch('https://livestock-booking-platform.vercel.app/data.json');
  const animals = await res.json(); 
  console.log(animals)
  const sortedAnimals = [...animals].sort((a, b) => {
    if (sort === "low") return a.price - b.price;
    if (sort === "high") return b.price - a.price;
    return 0;
  });
  return (
    <div>
      <h1 className='text-2xl font-bold my-5'>All Animals</h1>
      <Link href="?sort=low">Low → High</Link> |{" "}
      <Link href="?sort=high">High → Low</Link>
      <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5'>
        {sortedAnimals.map(animal => (
          <AnimalCard key={animal.id} animal={animal} />
        ))}
      </div>
    </div>
  );
};

export default AllAnimalsPage;