import Banner from "@/components/Banner";
import TopGenerations from "@/components/TopGenerations";
import Image from "next/image";

export const metadata = {
  title: "livestock-booking-platform home page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Banner></Banner>
      <TopGenerations></TopGenerations>
    </div>
  );
}
